[build]
  functions = "./functions"
  publish = "public"
  command = "npm install gulp && gulp"

[dev]
  publish = "public"

[[redirects]]
  from = "/payments/*"
  to = "/payments.html"
  status = 200

[[redirects]]
  from = "/pay-order/*"
  to = "/pay-order.html"
  status = 200